<template>
  <div class="flex gap-5 w-full">
    <div class="p-5 bg-white rounded-lg shadow-md h-fit">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Aperiam dolor sunt natus deleniti distinctio. Id, repellendus fugiat qui similique nam atque quidem, non molestiae necessitatibus veniam assumenda quam placeat. Accusantium, accusamus? Quasi repudiandae architecto nulla iste totam, quod eveniet non provident fugit maxime? Ea ullam aliquam corrupti dicta. Labore, delectus hic voluptatibus laborum praesentium architecto accusamus reiciendis eos illum explicabo? Libero amet cumque doloremque expedita numquam fugit minima modi assumenda perspiciatis nulla rem voluptas, accusamus dolore nisi quas ipsa excepturi a, aspernatur ad? Nobis optio ab iste vero unde delectus? Necessitatibus ipsam nostrum est molestias, error quasi aspernatur adipisci ab.</div>
    <div class="p-5 bg-white rounded-lg shadow-md h-fit">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Incidunt, placeat aliquam! Adipisci quae, ex dolor possimus neque iusto soluta suscipit, veniam numquam harum quo tempora provident excepturi aliquid hic amet voluptates! Iusto, aperiam! Ex harum quidem autem nisi aspernatur, modi ullam enim dolores facilis quibusdam ipsum impedit repellendus, atque illo iure, optio incidunt tempore facere aut. Itaque autem consectetur voluptatibus magni. Praesentium minus molestias dolor dolore, ut voluptas facere nobis repellat vitae expedita omnis. Consequuntur ex dolorem aperiam tempora quis commodi, inventore obcaecati dolore corrupti iste? Tempora reiciendis, ex soluta inventore nemo cum facere praesentium asperiores? Sapiente minus placeat blanditiis, neque eligendi vero animi veritatis aut. Quas asperiores dicta sequi libero mollitia, velit eligendi laborum tempora recusandae sint enim ipsa, eveniet consequatur suscipit quibusdam quaerat odit? Temporibus maiores tempora vel pariatur corrupti, ea quos at expedita exercitationem suscipit nobis molestias consectetur dignissimos eveniet deleniti, culpa dolores, doloribus error. Laboriosam, beatae.</div>
    <div class="p-5 bg-white rounded-lg shadow-md h-fit">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Commodi sit nesciunt facere provident dolores qui laborum ea consequatur et laboriosam nobis, modi nostrum aliquam animi magnam, placeat beatae, ducimus esse tenetur odio corporis autem. Iste saepe officia, consequatur tenetur a voluptas dicta obcaecati eius vel placeat, asperiores sapiente natus laborum nesciunt! Temporibus facere quisquam explicabo soluta. Facere deserunt perferendis, iste beatae cumque mollitia maiores dolor quo hic dolore quos, repudiandae harum, officiis rem magni nam consequatur consequuntur eaque nulla explicabo tempore asperiores. Accusantium totam, quis beatae voluptate repellendus necessitatibus natus sed numquam, illum fugiat quod deleniti nulla ipsam itaque nisi ut excepturi rem, quos blanditiis quaerat sit eius cum exercitationem? Sed ut, nihil accusantium earum ab molestias ad est dolorem.</div>
  </div>
</template>

<script setup></script>

<style scoped></style>
